// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

function isNewSupabaseApiKey(value: string): boolean {
  return value.startsWith('sb_publishable_') || value.startsWith('sb_secret_');
}

function createSupabaseFetch(supabaseKey: string): typeof fetch {
  return (input, init) => {
    const headers = new Headers(
      typeof Request !== 'undefined' && input instanceof Request ? input.headers : undefined,
    );

    if (init?.headers) {
      new Headers(init.headers).forEach((value, key) => headers.set(key, value));
    }

    // New Supabase API keys are opaque strings, not bearer JWTs.
    if (isNewSupabaseApiKey(supabaseKey) && headers.get('Authorization') === `Bearer ${supabaseKey}`) {
      headers.delete('Authorization');
    }

    headers.set('apikey', supabaseKey);
    return fetch(input, { ...init, headers });
  };
}

// ---------------------------------------------------------------------------
// Null / no-op client — returned when Supabase credentials are not configured.
// Every method returns a safe empty response so the app renders without crashing.
// ---------------------------------------------------------------------------
function createNullClient() {
  const noopSubscription = { unsubscribe: () => {} };

  // A chainable query builder stub that always resolves to { data: [], error: null }
  function queryStub(): any {
    const stub: any = {
      select: () => stub,
      insert: () => stub,
      update: () => stub,
      upsert: () => stub,
      delete: () => stub,
      eq: () => stub,
      neq: () => stub,
      gt: () => stub,
      lt: () => stub,
      gte: () => stub,
      lte: () => stub,
      like: () => stub,
      ilike: () => stub,
      in: () => stub,
      is: () => stub,
      not: () => stub,
      or: () => stub,
      order: () => stub,
      limit: () => stub,
      range: () => stub,
      single: () => Promise.resolve({ data: null, error: null }),
      maybeSingle: () => Promise.resolve({ data: null, error: null }),
      then: (resolve: (v: any) => any) => Promise.resolve({ data: [], error: null }).then(resolve),
    };
    return stub;
  }

  // Storage bucket stub
  function storageBucketStub() {
    return {
      upload: async () => ({ data: null, error: null }),
      download: async () => ({ data: null, error: null }),
      remove: async () => ({ data: null, error: null }),
      list: async () => ({ data: [], error: null }),
      createSignedUrl: async () => ({ data: null, error: { message: 'Supabase not configured' } }),
      getPublicUrl: () => ({ data: { publicUrl: '' } }),
    };
  }

  return {
    auth: {
      getSession: async () => ({ data: { session: null }, error: null }),
      getUser: async () => ({ data: { user: null }, error: null }),
      onAuthStateChange: (_event: any, callback?: any) => {
        // Fire INITIAL_SESSION with null so useAuth settles immediately
        if (typeof callback === 'function') {
          Promise.resolve().then(() => callback('INITIAL_SESSION', null));
        }
        return { data: { subscription: noopSubscription } };
      },
      signUp: async () => ({
        data: { user: null, session: null },
        error: { message: 'Supabase is not configured. Add VITE_SUPABASE_URL and VITE_SUPABASE_PUBLISHABLE_KEY to connect.' },
      }),
      signInWithPassword: async () => ({
        data: { user: null, session: null },
        error: { message: 'Supabase is not configured. Add VITE_SUPABASE_URL and VITE_SUPABASE_PUBLISHABLE_KEY to connect.' },
      }),
      signInWithOAuth: async () => ({
        data: { provider: 'google', url: null },
        error: { message: 'Supabase is not configured.' },
      }),
      signOut: async () => ({ error: null }),
      resend: async () => ({ error: { message: 'Supabase is not configured.' } }),
      resetPasswordForEmail: async () => ({ error: { message: 'Supabase is not configured.' } }),
      updateUser: async () => ({ data: { user: null }, error: { message: 'Supabase is not configured.' } }),
    },
    from: (_table: string) => queryStub(),
    storage: {
      from: (_bucket: string) => storageBucketStub(),
    },
    channel: (_name: string) => ({
      on: () => ({ subscribe: () => ({ unsubscribe: () => {} }) }),
      subscribe: () => ({ unsubscribe: () => {} }),
    }),
    removeChannel: () => {},
  } as unknown as ReturnType<typeof createSupabaseClient>;
}

function createSupabaseClient() {
  // Use import.meta.env for client-side (Vite build-time replacement)
  // Fall back to process.env for SSR (server-side rendering)
  const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || process.env.SUPABASE_URL;
  const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || process.env.SUPABASE_PUBLISHABLE_KEY;

  if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
    const missing = [
      ...(!SUPABASE_URL ? ['SUPABASE_URL'] : []),
      ...(!SUPABASE_PUBLISHABLE_KEY ? ['SUPABASE_PUBLISHABLE_KEY'] : []),
    ];
    console.warn(`[Supabase] Missing env var(s): ${missing.join(', ')}. Running in no-op mode — connect Supabase to enable auth and data.`);
    return createNullClient();
  }

  return createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    global: {
      fetch: createSupabaseFetch(SUPABASE_PUBLISHABLE_KEY),
    },
    auth: {
      storage: typeof window !== 'undefined' ? localStorage : undefined,
      persistSession: true,
      autoRefreshToken: true,
    }
  });
}

let _supabase: ReturnType<typeof createSupabaseClient> | undefined;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
export const supabase = new Proxy({} as ReturnType<typeof createSupabaseClient>, {
  get(_, prop, receiver) {
    if (!_supabase) _supabase = createSupabaseClient();
    return Reflect.get(_supabase, prop, receiver);
  },
});
